name: athkarix
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter_lints: ^2.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  #flutter_share: ^2.0.0
  share_plus: ^10.0.0
  get: ^4.6.5
  hex: ^0.2.0
  intl: ^0.20.1
  rename_app: ^1.6.1
  shared_preferences: ^2.5.0
  url_launcher: ^6.2.5
  flutter_native_splash: ^2.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/dua.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  flutter_lints: ^4.0.0
  #uses-material-design: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/91k.jpg
    - assets/images/athkari5.jpg
    - assets/json/
    - lib/core/data/json/

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri/Amiri-Bold.ttf
          weight: 700

    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
